Optimization, error handlers
rareweave/tradeable-mintable-smartweave-nft pull request #1
Opened 2023-02-17 16:54 UTC by Alexcitten

**Possible error handlers were added, optimization was done, and a bit of beauty was added.**

The initialization of Arweave was moved outside of the `deployContract` function, since there is no need to initialize it several times.
Then created a separate `deployContract` function to handle the deployment process. Renamed some variables for clarity. And also added error handling for the deploy method

I used ES6 to import individual functions, and simplified operators to check input and error handling.
Created a separate functionMap object to map input functions to the corresponding function implementations.
Useful to have error handling when the input function is not in the function map.
Renamed the change-price function to `changePrice` to follow the standard naming conventions in the camel case, I understand that such "cutting" of code is not necessary, but why not.

Used destructive assignment to get the input and caller properties from the action object, and the default value syntax to set the target variable to an undefined value if it is not present in the input object looks nice.

I also changed the `ContractAssert` condition so that it is not executed when the target is false, moved the calculation of the balance variable after the `ContractAssert` condition to avoid unnecessary calculations when the target is not present.
Simplified the balance calculation with the `||` operator so that the default value is 0 when the target is not present in the balance object.

I used destructive assignment to get the input and caller properties from the action object, and changed the second ContractAssert condition so that it doesn't execute if target is false.
A good solution is to move `balances[caller] -= qty` before `balances[target] += qty` to avoid double-counting when caller and target are the same.
Added check to remove caller from balances when caller no longer owns tokens.

2023-02-17 17:48 UTC, angrymouse requested changes
Can you also add contract code address to output? It's useful property

2023-02-17 17:49 UTC, angrymouse commented on src/contract.js
> +import transfer from "./functions/transfer.js";
Will imports work with esbuild's IIFE setup?
It can potentially break execution

2023-02-17 17:50 UTC, angrymouse commented on src/functions/balance.js
>  module.exports = async function (state, action) {
if you use ESM import, use ESM export as well, or it doesn't work

2023-02-17 20:30 UTC, Alexcitten commented
Yes, you are correct.Я I should have thought about that, and checked it out.
Kind of fixed it.

2023-02-17 23:53 UTC, angrymouse commented on deploy.js
> +  const contractCode = await arweave.transactions.getData(srcTxId, { decode: true, string: true });
You don't have to re-download code... What I meant is showing Transaction ID of code that you've uploaded to arweave

2023-02-20 10:54 UTC, Alexcitten commented
I hope I've done everything right now.
A description of each improvement can be found in the comet description

2023-02-22 09:59 UTC, merged